version: '3'

services:
  nest-back:
    build:
      context: .
      dockerfile: ./nest-project/dockerfile
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
    - ./nest-project:/usr/src/app
  nuxt-front:
    build:
      context: .
      dockerfile: ./nuxt-app/dockerfile
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
    - ./nuxt-app:/usr/src/app