FROM node:lts

# アプリケーションディレクトリを作成する
WORKDIR /usr/src/app

# アプリケーションの依存関係をインストールする
# ワイルドカードを使用して、package.json と package-lock.json の両方が確実にコピーされるようにします。
# 可能であれば (npm@5+)
# dockercompose.ymlからの相対パスで指定してるっぽい？→docker-compose.ymlで指定したコンテキストルートからの相対パスで記述する
COPY ./nest-project .

RUN npm install
# 本番用にコードを作成している場合
# RUN npm install --only=production

# アプリケーションのソースをバンドルする
EXPOSE 4000

# CMD [ "npx","prisma", "generate" ]
CMD [ "npm","run", "start" ]